context:
  version: 1.0.0rc1
  build_number: '0'

package:
  name: pollen-bmi088-imu-library
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/pollen-bmi088-imu-library/pollen_bmi088_imu_library-${{ version }}.tar.gz
  sha256: 6a82eafa448807a87c7a9e1ed8ef395b0ce5f2f57fa536b5b3a3f428e72d8fcf

build:
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
  - python >=3.10
  - setuptools
  - pip
  run:
  - python >=3.10
  - smbus3 ==0.5.5
  - numpy
  - ahrs

tests:
- python:
    imports:
    - pollen_bmi088_imu_library
    pip_check: true

about:
  description: "# Pollen BMI088 IMU library\n\nA simple library to get data from the BMI088 IMU in i2c\n\n## Installation \n\nFrom PyPi: \n\n`pip install pollen_bmi088_imu_library`\n\nFrom the repo:\n\n`pip install -e .`\n\n## Usage \n\nImport and use the library like this \n\n```python\nfrom bmi088 import BMI088\n\naccelerometer = imu.read_accelerometer(m_per_s2=...)\n\ngyroscope = imu.read_gyroscope(deg_per_s=...)\n\nquat = imu.get_quat(dt)\n\n```\n"
